[package]
name = "decentralized-access-control"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
iroh = "1.1.0"
iroh-blobs = "0.103.0"
iroh-docs = "0.101.0"
iroh-gossip = "0.101.0"
serde_json = "1.0.151"
tempfile = "3.27.0"
tokio = {version = "1", features = ["full"]}
tokio-stream = "0.1.19"
tokio-util = "0.7.19"
